title: Ania BENALI
logo: assets/img/headshot_circle.png  # Retirer le '/' au début
description: PORTFOLIO de Ania BENALI
theme: jekyll-theme-hyde
plugins:
  - jekyll-seo-tag         # Plugin pour améliorer le SEO de ton site
  - jekyll-paginate        # Plugin pour gérer la pagination
  - jekyll-feed            # Plugin pour générer un flux RSS

